### ISSUE TITLE
给点建议

### ISSUE THREAD

**Issue by Bingxiusmall** [XYZscratcher/funny-translate#1]
1、建议readme.md放一个英文版，当然如果你就是给ccw社区的人看的不用管
2、如果翻译多个词可以用一定的短句翻译，因为形容词什么的直接翻译怪怪的

**Comment by XYZscratcher** [comment]
感谢你的建议。
1、英文版以后会搞。
2、目前实现有点难度，而且这只是一个~~闲着没事做~~搞笑的翻译器，还是放在以后去做。目前重点还是放在多句话的翻译和提高运行速度。

**Comment by Bingxiusmall** [comment]
你提高速度的话可以试一下做一个爬虫程序另行直接把数据全都爬下来，这样更快
